// React Native side of the detector. Owns the Bare worklet lifecycle and the request/response
// correlation over BareKit IPC. Nothing here touches pixels: the JPEG goes in, JSON comes back.
import { Worklet } from "react-native-bare-kit";
// @ts-ignore - plain ESM shared with the worklet and with node --test
import { RPC, encodeFrame, createFrameReader } from "../../worklet/protocol.mjs";
// @ts-ignore - generated by `npm run bundle:worklet`
import bundleBase64 from "../../worklet/bundle.js";

export type Health = {
  bare: string | null;
  platform: string | null;
  arch: string | null;
  addon: string;
  providers: string[];
  model: string | null;
  loaded: boolean;
  size: number;
};

export type Detection = {
  label: string;
  cls: number;
  score: number;
  box: number[];
  bottomCenter: number[];
  w: number;
  h: number;
  sig?: number[];
  dwell?: number;
};

export type FrameResult = {
  width: number;
  height: number;
  vehicles: Detection[];
  tracks: any[];
  perBand: Record<string, any>;
  meanLuma: number;
  energy: number | null;
  ms: { decode: number; infer: number; total: number };
};

const TIMEOUT_MS = 30000;

function base64ToBytes(b64: string): Uint8Array {
  // No atob and no Buffer guaranteed on RN; decode explicitly.
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  const lookup = new Uint8Array(256);
  for (let i = 0; i < chars.length; i++) lookup[chars.charCodeAt(i)] = i;
  const len = b64.length;
  let pad = 0;
  if (b64[len - 1] === "=") pad++;
  if (b64[len - 2] === "=") pad++;
  const out = new Uint8Array((len / 4) * 3 - pad);
  let p = 0;
  for (let i = 0; i < len; i += 4) {
    const a = lookup[b64.charCodeAt(i)];
    const b = lookup[b64.charCodeAt(i + 1)];
    const c = lookup[b64.charCodeAt(i + 2)];
    const d = lookup[b64.charCodeAt(i + 3)];
    if (p < out.length) out[p++] = (a << 2) | (b >> 4);
    if (p < out.length) out[p++] = ((b & 15) << 4) | (c >> 2);
    if (p < out.length) out[p++] = ((c & 3) << 6) | d;
  }
  return out;
}

export class DetectorClient {
  private worklet: any = null;
  private pending = new Map<number, { resolve: (v: any) => void; reject: (e: any) => void; timer: any }>();
  private nextId = 1;
  private readyPromise: Promise<Health> | null = null;

  /** Start the worklet and wait for its `ready` frame. Idempotent. */
  start(): Promise<Health> {
    if (this.readyPromise) return this.readyPromise;
    this.readyPromise = new Promise<Health>((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error("worklet did not become ready in 30s")), TIMEOUT_MS);
      try {
        this.worklet = new Worklet();
        const read = createFrameReader((header: any) => {
          if (header.type === "ready") {
            clearTimeout(timer);
            if (header.ok) resolve(header as Health);
            else reject(new Error(header.error || "worklet failed to initialise"));
            return;
          }
          const p = this.pending.get(header.id);
          if (!p) return;
          this.pending.delete(header.id);
          clearTimeout(p.timer);
          if (header.ok) p.resolve(header);
          else p.reject(Object.assign(new Error(header.error || "detector error"), { code: header.code }));
        });
        this.worklet.start("/app.bundle", base64ToBytes(bundleBase64));
        this.worklet.IPC.on("data", (d: any) => read(new Uint8Array(d)));
        this.worklet.IPC.on("error", (e: any) => reject(e));
      } catch (e) {
        clearTimeout(timer);
        reject(e);
      }
    });
    return this.readyPromise;
  }

  private request(header: any, payload: Uint8Array | null = null): Promise<any> {
    const id = this.nextId++;
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        this.pending.delete(id);
        reject(new Error(`${header.type} timed out after ${TIMEOUT_MS}ms`));
      }, TIMEOUT_MS);
      this.pending.set(id, { resolve, reject, timer });
      const full = { ...header, id, payloadLen: payload ? payload.byteLength : 0 };
      this.worklet.IPC.write(encodeFrame(full, payload));
    });
  }

  health(): Promise<Health> {
    return this.request({ type: RPC.HEALTH });
  }

  /** Load the ONNX model. `modelPath` must be a plain filesystem path, not a file:// URI. */
  loadModel(modelPath: string): Promise<any> {
    return this.request({ type: RPC.LOAD, modelPath });
  }

  detect(jpeg: Uint8Array, opts: { bands?: any[]; scales?: any; tracks?: any[]; passes?: string[] } = {}): Promise<FrameResult> {
    return this.request(
      {
        type: RPC.DETECT,
        bands: opts.bands ?? [],
        scales: opts.scales ?? {},
        tracks: opts.tracks ?? [],
        passes: opts.passes ?? ["full"],
      },
      jpeg
    );
  }

  unload(): Promise<any> {
    return this.request({ type: RPC.UNLOAD });
  }

  terminate() {
    for (const [, p] of this.pending) {
      clearTimeout(p.timer);
      p.reject(new Error("worklet terminated"));
    }
    this.pending.clear();
    this.readyPromise = null;
    try {
      this.worklet?.terminate?.();
    } catch {}
    this.worklet = null;
  }
}

export const detector = new DetectorClient();
